web/project/users/views.py
# project/users/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
from twilio.rest import TwilioRestClient

from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm, NewScreening
from project import db, mail, app
from project.models import User, Screening



################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)


##########################
#### Screening routes ####
##########################

@users_blueprint.route('/movement_screenings')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('movement_screenings.html', users=users)
    return redirect(url_for('users.login'))


@users_blueprint.route('/get_latest_screening')
def get_latest_screening():
    pass


@users_blueprint.route('/get_all_screenings')
@login_required
def get_all_screenings():
    pass

@users_blueprint.route('/new_screening', methods=['POST', 'GET'])
def new_screening():
    form = NewScreening(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            screening = Screening(user.id, form.shoulder_flexion.data, form.shoulder_rotation.data,
                                form.ankle_mobility.data, form.supine_squat.data, form.leg_raise.data, form.overhead_squat.data,
                                form.arms_extended_squat.data, form.foot_collapse.data)
            db.session.add(screening)
            db.session.commit()
            flash("Your new screening has been recorded! Below are your suggested movement vitamins!", 'success')
            return redirect(url_for('vitamins.suggested_vitamins'))
    else:
        return render_template('movement_screening.html', form=form)


#####################
#### User routes ####
#####################

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                if 'ACCOUNT_SID' in app.config and not app.config['TESTING']:
                    send_new_user_text_message(new_user.email)
                flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('vitamins.home_page', target_area='All'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)



@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('vitamins.home_page', target_area='All'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


    
@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('vitamins.home_page'))


@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.', 'success')
        else:
            flash('Your email address must be confirmed before attempting a password reset.', 'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():

web/project/vitamins/views.py
# project/vitamins/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint, request, redirect, url_for, flash, abort, jsonify
from flask_login import current_user, login_required
from project import db, images, app
from project.models import Vitamin, User, Screening
from .forms import AddVitaminsForm, EditVitaminsForm
from random import random
from twilio.rest import TwilioRestClient
from project.logic import suggest_vitamins


################
#### config ####
################

vitamins_blueprint = Blueprint('vitamins', __name__)


##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')



################
#### routes ####
################

@vitamins_blueprint.route('/')
def home_page():
    public_vitamins = Vitamin.query.filter((Vitamin.link != "")).limit(4)
    return render_template('home_page.html', public_vitamins=public_vitamins)

@vitamins_blueprint.route('/vitamins/<target_area>')
def all_vitamins(target_area='All'):
    if target_area in ['Hips', 'Ankle', 'Shoulder Flexion', 'Shoulder Rotation', 'Foot', 'Upper Body']:
        my_vitamins = Vitamin.query.filter((Vitamin.target_area == target_area))
        return render_template('all_vitamins.html', all_vitamins=my_vitamins, target_area=target_area)
    elif target_area == 'All':
        my_vitamins = Vitamin.query.filter((Vitamin.target_area != ""))
        return render_template('all_vitamins.html', all_vitamins=my_vitamins, target_area=target_area)
    else:
        flash('ERROR! Invalid target area selected.', 'error')

    return redirect(url_for('vitamins.home_page'))

@vitamins_blueprint.route('/suggested')
def suggested_vitamins():
    latest_screening = Screening.query.filter(Screening.user_id == current_user.id).first_or_404()
    target_areas, focus_areas, squat_tag = suggest_vitamins(latest_screening)
    my_vitamins = Vitamin.query.filter((Vitamin.target_area.in_(target_areas)))
    return render_template('all_vitamins.html', all_vitamins=my_vitamins)


@vitamins_blueprint.route('/vitamin/<vitamin_id>')
def vitamin_details(vitamin_id):
    vitamin = Vitamin.query.filter_by(id=vitamin_id).first_or_404()
    return render_template('vitamin_detail.html', vitamin=vitamin)
  
  

web/project/templates/410.html
{% extends "layout.html" %}

{% block content %}

  <h1>Gone</h1>
  <h4>The target resource is no longer available at the origin server and that this condition is likely to be permanent.</h4>
  <h4><a href="{{ url_for('vitamins.home_page') }}">Movement Vitamins</a></h4>

{% endblock %}

web/project/templates/_form_macros.html
{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_field_without_label(field) %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_boolean_field(field) %}
  <dd>{{ field(**kwargs)|safe }} {{ field.label }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_errors(field) %}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

web/project/templates/admin_view_users.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }} </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

web/project/templates/all_vitamins.html
{% extends "layout.html" %} {% block content %}

<div class="all-vitamins">
    <div class="page-header">
        <h2>Vitamins</h2>
    </div>

    <div class="container">
        {% if all_vitamins.count() == 0 %}
        <h5>No vitamins have been created!</h5>
        {% else %}
        <ul class="media-list">
            {% for vitamin in all_vitamins %}
            <li class="media">
                <div class="media-left">
                    <a class="media-left" href="{{ url_for('vitamins.vitamin_details', vitamin_id=vitamin.id) }}">
                        <img class="media-object" src="{{getYoutubeThumbnailUrl(vitamin.link)}}" style="width:64;height:64px;">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="{{ url_for('vitamins.vitamin_details',vitamin_id=vitamin.id) }}">{{ vitamin.name }}</a>
                        <span class="label label-info" style="font-size:10px;">{{vitamin.target_area}}</span>
                        {% if vitamin.mobility %}
                            <span class="label label-success" style="font-size:10px;">Mobility</span>
                        {% endif %}
                        {% if vitamin.stability %}
                            <span class="label label-warning" style="font-size:10px;">Stability</span>
                        {% endif %}

                    </h4>
                    {{ vitamin.description }}
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

web/project/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>

  <p>Current Email: {{ current_user.email }}</p>
  <p>Please enter your new email address:</p>
  <form action="{{ url_for('users.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field_without_label(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}

Your account on Movement Vitamins was successfully created.<br>
Please click the link below to confirm your email address and<br>
activate your account:
 
<p>
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
</p>

web/project/templates/home_page.html
{% extends "layout.html" %} {% block content %}

<div class="user-profile">
    <div class="container">
        <div class="jumbotron">
            <h1>Movement Vitamins</h1>
            <p>The one stop shop to move better!</p>
        </div>

        {% if public_vitamins.count() > 0 %}
        <h3>Vitamins</h3>
        <div class="row">
            {% for vitamin in public_vitamins %}
            <div class="col-xs-6 col-md-3">
                <tr>
                    <td>{{ vitamin.name }}</td>
                    <a href="{{ url_for('vitamins.vitamin_details', vitamin_id=vitamin.id) }}" class="thumbnail">
                        <img class="media-object" src="{{getYoutubeThumbnailUrl(vitamin.link)}}" style="width:260px;height:170px;">
                    </a>
                </tr>
            </div>
            {% endfor %}
        </div>
        {% endif %}

    </div>
    <!-- /container -->
</div>

{% endblock %}

web/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Movement Vitamins">
    <meta name="author" content="Movement Vitamins Team">

    <title>Movement Vitamins</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#vitamins-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

                <a class="navbar-brand" href="{{ url_for('vitamins.home_page') }}">Movement Vitamins</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="vitamins-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vitamins<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Shoulder Flexion') }}">Shoulder Flexion</a></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Shoulder Rotation') }}">Shoulder Rotation</a></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Hips') }}">Hips</a></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Foot') }}">Foot</a></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Ankle') }}">Ankle</a></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='Upper Body') }}">Upper Body</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('vitamins.all_vitamins', target_area='All') }}">All vitamins</a></li>
                        </ul>
                    </li>
                    {% if current_user.is_authenticated %} {% if current_user.role == "admin" %}
                    <li><a href="{{ url_for('users.admin_view_users') }}">Movement Screenings</a></li>
                    {% else %}
                    <li><a href="{{ url_for('users.new_screening') }}">Movement Screening</a></li>
                    {% endif %} {% else %}
                    <li><a href="{{ url_for('users.register') }}">Register</a></li>
                    <li><a href="{{ url_for('users.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('users.user_profile') }}">User Profile</a></li>
                    <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
                    {% else %}
                    <li><a href="#">Welcome!</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
        <div class="content">

            <!-- flash messages -->
            {% for error_message in get_flashed_messages(category_filter=["error"]) %}
            <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
            {% endfor %} {% for success_message in get_flashed_messages(category_filter=["success"]) %}
            <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
            {% endfor %} {% for info_message in get_flashed_messages(category_filter=["info"]) %}
            <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
            {% endfor %}

            <!--
        {% for debug_message in get_flashed_messages(category_filter=["debug"]) %}
          <div class="alert alert-info alert-dismissible">{{ debug_message }}</div>
        {% endfor %} -->
            <!-- child template -->
            {% block content %} {% endblock %}


        </div>
        <div class="footer">
            <hr>
            <p>Momement Vitamins Team - 2018</p>
        </div>
    </div>
    <!-- /.container -->


    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>

</html>

web/project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
  <form action="{{ url_for('users.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Log In</button>
  </form>
  <br>
  <p><em>Need an account? </em><a href="/register">Signup!!</a></p>
  <p><em>Forgot your password? </em><a href="/reset">Reset!!</a></p>
</div>

{% endblock %}

web/project/templates/movement_screening.html
{% extends "layout.html" %} {% from "_form_macros.html" import render_errors %} {% block content %}

<div class="edit-screening">
    <div class="page-header">
        <h2>New Screening</h2>
    </div>

    <div class="container">
        <form action="{{ url_for('users.new_screening') }}" method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}

            <style>
                    .screening_td {
                       padding-left: 10px;
                       padding-bottom: 30px;
                    }

                    .screening_th {
                       padding-bottom: 30px;
                    }

                    .screening_label {
                        font-size:20px;
                    }
            </style>

            <table>
                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="shoulder_flexion">Shoulder Flexion</label></th>
                    {% for subfield in form.shoulder_flexion %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" class="screening_label" for="shoulder_rotation">Shoulder Rotation</label></th>
                    {% for subfield in form.shoulder_rotation %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="ankle_mobility">Ankle Mobility</label></th>
                    {% for subfield in form.ankle_mobility %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="supine_squat">Suspine Squat</label></th>
                    {% for subfield in form.supine_squat %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>
                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="leg_raise">Active Straight Leg Raise</label></th>
                    {% for subfield in form.leg_raise %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="overhead_squat">Overhead Squat</label></th>
                    {% for subfield in form.overhead_squat %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                    <th class="screening_th"><label class="screening_label" for="arms_extended_squat">Arms Extended Squat</label></th>
                    {% for subfield in form.arms_extended_squat %}
                            <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                    {% endfor %}
                </tr>

                <tr class="screening_tr">
                        <th class="screening_th"><label class="screening_label" for="foot_collapse">Foot Collapse</label></th>
                        {% for subfield in form.foot_collapse %}
                                <td class="screening_td">{{ subfield }} {{ subfield.label }}</td>
                        {% endfor %}
                    </tr>
            </table>

            <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit Screening</button>
                </div>
            </div>

        </form>
    </div>
</div>

{% endblock %}

web/project/templates/movment_screenings.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }} </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

web/project/templates/password_reset_email.html
{% extends "layout.html" %} {% from "_form_macros.html" import render_field %} {% block content %}

<div class="reset-pass">
    <div class="page-header">
        <h2>Email Address:</h2>
    </div>
    <form action="{{ url_for('users.reset') }}" method="POST">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.email, placeholder="Enter Email Address") }}
        </dl>
        <button class="btn btn-sm btn-success" type="submit">Submit</button>
    </form>
</div>

{% endblock %}

web/project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Please Register Your New Account</h2>
  </div>
  <form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create New Account</button>
  </form>
</div>

{% endblock %}

web/project/templates/reset_password_with_token.html
{% extends "layout.html" %} {% from "_form_macros.html" import render_field %} {% block content %}

<div class="reset-password">
    <div class="page-header">
        <h2>New Password:</h2>
    </div>
    <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.password, placeholder="Enter New Password") }}
        </dl>
        <button class="btn btn-sm btn-success" type="submit">Update</button>
    </form>
</div>

{% endblock %}